#!/usr/bin/env python3
"""Emit a per-volume step-1 config that inherits `1_affinity.yaml`.

`1_affinity.yaml` is written for a single volume; the batch needs eight. Rather
than duplicate it, each volume gets a four-line override file whose `_base_` is
the absolute path to the tutorial config, so the recipe stays in one place.

    python tutorials/neuron_liconn_moe/make_volume_config.py --volume <name>
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import yaml

sys.path.insert(0, str(Path(__file__).resolve().parent))
import volumes as V  # noqa: E402

HERE = Path(__file__).resolve().parent


def write_config(name: str, out_dir: Path) -> Path:
    p = V.plan(name)
    out_dir.mkdir(parents=True, exist_ok=True)
    cfg = {
        "_base_": [str(HERE / "1_affinity.yaml")],
        "experiment_name": f"liconn_moe_affinity_{name}",
        "params": {
            "data": {
                "volume": str(V.PREPARED),
                "image": f"{name}.h5",
                # Effective spacing of the prepared volume, not the nominal
                # [24,18,18] target; see volumes.py.
                "resolution_zyx": [float(round(v, 6)) for v in p["spacing_zyx"]],
            },
            "artifacts": {
                "volume_name": name,
                "volume_dir": str(V.TEST_OUT / name),
            },
        },
    }
    path = out_dir / f"{name}_1_affinity.yaml"
    path.write_text(
        "# GENERATED by make_volume_config.py -- edit 1_affinity.yaml instead.\n"
        + yaml.safe_dump(cfg, sort_keys=False)
    )
    return path


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--volume")
    ap.add_argument("--index", type=int, help="index into volumes.PENDING")
    ap.add_argument("--out-dir", type=Path, default=V.OUT_ROOT / "configs")
    a = ap.parse_args()
    name = a.volume or V.PENDING[a.index]
    print(write_config(name, a.out_dir))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
